# Generated by Django 6.0.3 on 2026-04-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
